### ISSUE TITLE
Move large files fom the website to github

### ISSUE THREAD

**Issue by martynpclark** [NCAR/summa#87] opened 2015-07-24 14:36 UTC
Move large files from the website to github making use of the git Large File Storage (LFS) capabilities

**Comment by bartnijssen** [comment] 2016-08-18 21:46
Try this - but this did not quite work as intended. We need a different solution for the large files other than github. Closing the issue for now and reopening another one for large file storage

**Closed by bartnijssen** 2016-08-18 21:46 UTC
